# Default values for s3www.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: y4m4/s3www
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.9.0"


service:
  type: ClusterIP  # Changed from LoadBalancer to ClusterIP
  port: 8080
  annotations: {}

ingress:
  enabled: false
  className: "gce"  # GCP Ingress class
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "s3www-static-ip"  # Optional: Use a static IP
    networking.gke.io/managed-certificates: "s3www-cert"  # For managed SSL certificates
    kubernetes.io/ingress.allow-http: "false"  # Force HTTPS
  hosts:
    - host: s3www.example.com  # Replace with your domain
      paths:
        - path: /
          pathType: ImplementationSpecific
          servicePort: 8080
  tls: []  # Not needed if using managed certificates

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


# s3www specific configurations
s3www:
  endpoint: "http://minio:9000"  # Using Kubernetes service name
  bucket: "up42"
  address: "0.0.0.0:8080"

# Metrics configuration
metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 15s
    scrapeTimeout: 10s
    labels: {}
    # Additional labels for ServiceMonitor
    # Example:
    #   release: prometheus
    metricRelabelings: []
    relabelings: []
