apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3www.fullname" . }}-credentials
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.s3www.accessKey | b64enc | quote }}
  secret-key: {{ .Values.s3www.secretKey | b64enc | quote }} 