# Default values for minio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/minio/minio
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "RELEASE.2025-04-03T14-56-28Z-cpuv1"


securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

service:
  type: ClusterIP  # Changed from LoadBalancer to ClusterIP
  apiPort: 9000
  consolePort: 9001
  annotations: {}

ingress:
  enabled: false
  className: "gce"  # GCP Ingress class
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "minio-static-ip"  # Optional: Use a static IP
    networking.gke.io/managed-certificates: "minio-cert"  # For managed SSL certificates
    kubernetes.io/ingress.allow-http: "false"  # Force HTTPS
  hosts:
    - host: minio.example.com  # Replace with your domain
      paths:
        - path: /
          pathType: ImplementationSpecific
          servicePort: 9000  # API port
        - path: /console
          pathType: ImplementationSpecific
          servicePort: 9001  # Console port
  tls: []  # Not needed if using managed certificates

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi



autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Minio specific configurations
minio:
  args:
    - server
    - /data
    - --console-address
    - ":9001"

persistence:
  enabled: true
  mountPath: /data
  size: 10Gi
  accessMode: ReadWriteOnce

# Additional volumes on the output Deployment definition.
volumes:
  - name: data
    persistentVolumeClaim:
      claimName: minio-data

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: data
    mountPath: /data

nodeSelector: {}

tolerations: []

affinity: {}

# Metrics configuration
metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 15s
    scrapeTimeout: 10s
    labels: {}
    # Additional labels for ServiceMonitor
    # Example:
    #   release: prometheus
    metricRelabelings: []
    relabelings: []
