apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-credentials
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
data:
  root-user: {{ .Values.minio.rootUser | b64enc | quote }}
  root-password: {{ .Values.minio.rootPassword | b64enc | quote }} 